#!/usr/bin/env python3
import re
import sys
import os
from datetime import datetime
import html

def main():
    # Get environment variables
    pr_number = os.environ.get('PR_NUMBER', 'unknown')
    pr_title = os.environ.get('PR_TITLE', 'Unknown PR')
    pr_sha = os.environ.get('PR_SHA', 'unknown')
    existing_index_file = os.environ.get('EXISTING_INDEX', '')

    # Escape HTML characters in PR title
    pr_title_escaped = html.escape(pr_title.strip())

    # HTML template for PR card
    pr_card_template = f"""                          <div class="pr-card" data-pr="{pr_number}">
                              <a href="pr-{pr_number}/" class="pr-link">PR #{pr_number} Preview</a>
                              <div class="meta">
                                  <span class="badge">Active</span><br>
                                  {pr_title_escaped}<br>
                                  Updated: {datetime.now().strftime("%Y-%m-%d %H:%M UTC")} | Commit: {pr_sha[:8]}
                              </div>
                          </div>"""

    # Base HTML template
    base_html = """<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>OWASP WrongSecrets - PR Previews</title>
    <style>
        body {
            font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            margin: 40px;
            background-color: #f8f9fa;
        }
        .container { max-width: 1200px; margin: 0 auto; }
        .header { text-align: center; margin-bottom: 40px; }
        .pr-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(300px, 1fr)); gap: 20px; }
        .pr-card {
            background: white;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 2px 4px rgba(0,0,0,0.1);
            border-left: 4px solid #0366d6;
        }
        .pr-link { text-decoration: none; color: #0366d6; font-weight: bold; font-size: 1.2em; }
        .pr-link:hover { text-decoration: underline; }
        .meta { color: #666; font-size: 0.9em; margin-top: 10px; }
        .badge {
            background: #e1f5fe;
            color: #01579b;
            padding: 2px 8px;
            border-radius: 12px;
            font-size: 0.8em;
        }
        .no-previews {
            text-align: center;
            color: #666;
            font-style: italic;
            grid-column: 1 / -1;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="header">
            <h1>🔐 OWASP WrongSecrets</h1>
            <h2>Pull Request Previews</h2>
            <p>Static previews of pull requests for UI and template changes</p>
        </div>

        <div id="pr-list">
            <div class="pr-grid">
<!-- PR_CARDS_PLACEHOLDER -->
            </div>
        </div>

        <div style="text-align: center; margin-top: 40px; color: #666;">
            <p>
                <a href="https://github.com/OWASP/wrongsecrets" target="_blank">View Repository</a> |
                <a href="https://github.com/OWASP/wrongsecrets/pulls" target="_blank">All Pull Requests</a>
            </p>
            <small>Generated by GitHub Actions • Last updated: """ + datetime.now().strftime("%Y-%m-%d %H:%M UTC") + """</small>
        </div>
    </div>
</body>
</html>"""

    try:
        # Try to read existing index
        if existing_index_file and os.path.exists(existing_index_file):
            with open(existing_index_file, 'r') as f:
                existing_content = f.read()
            
            # Extract existing PR cards
            card_pattern = r'<div class="pr-card"[^>]*>.*?</div>\s*</div>'
            existing_cards = re.findall(card_pattern, existing_content, re.DOTALL)
            
            # Remove the current PR card if it exists
            filtered_cards = []
            for card in existing_cards:
                if f'data-pr="{pr_number}"' not in card:
                    filtered_cards.append(card)
            
            # Add current PR card at the beginning
            all_cards = [pr_card_template] + filtered_cards
            
        else:
            # No existing index, start fresh
            all_cards = [pr_card_template]

        # Generate final HTML
        if all_cards:
            cards_html = '\n'.join(all_cards)
        else:
            cards_html = '                          <div class="no-previews">No active PR previews</div>'
        
        final_html = base_html.replace('<!-- PR_CARDS_PLACEHOLDER -->', cards_html)
        
        with open('static-site/index.html', 'w') as f:
            f.write(final_html)
        
        print(f"Successfully updated index with PR #{pr_number}")
        
    except Exception as e:
        print(f"Error updating index: {e}")
        # Fallback to simple index
        fallback_html = base_html.replace('<!-- PR_CARDS_PLACEHOLDER -->', pr_card_template)
        with open('static-site/index.html', 'w') as f:
            f.write(fallback_html)
        print("Created fallback index")

if __name__ == "__main__":
    main()