FROM jeroenwillemsen/wrongsecrets:1.4.3-no-vault

ARG argBasedVersion="1.4.3"
ARG CANARY_URLS="http://canarytokens.com/terms/about/s7cfbdakys13246ewd8ivuvku/post.jsp,http://canarytokens.com/terms/about/y0all60b627gzp19ahqh7rl6j/post.jsp"
ENV APP_VERSION=$argBasedVersion
ENV K8S_ENV=Heroku(Docker)
ENV canarytokenURLs=$CANARY_URLS
ENV challengedockermtpath="/var/helpers"
ENV keepasspath="/var/helpers/alibabacreds.kdbx"
COPY .github/scripts/ /var/helpers
COPY src/test/resources/alibabacreds.kdbx /var/helpers
CMD java -Xms128m -Xmx128m -Xss512k -jar -Dserver.port=$PORT -XX:MaxRAMPercentage=75 -XX:MinRAMPercentage=25 -Dspring.profiles.active=without-vault application.jar
