FROM jeroenwillemsen/wrongsecrets:1.1.6-no-vault

ARG argBasedVersion="1.1.6"
ENV APP_VERSION=$argBasedVersion
ENV K8S_ENV=Heroku(Docker)
ENV challengedockermtpath="/var/helpers"
COPY .github/scripts/ /var/helpers
CMD java -Xms128m -Xmx128m -Xss512k -jar -Dserver.port=$PORT -XX:+UseContainerSupport -Dspring.profiles.active=without-vault application.jar
