FROM lscr.io/linuxserver/webtop:4.16-r0-ls72
LABEL NAME="OWASP WrongSecrets Web Desktop" MAINTAINER="Jeroen Willemsen"

RUN \
   echo "*** install kubectl ***" && \
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" &&\
    sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl &&\
    rm kubectl

RUN \
  echo "**** install packages ****" && \
  apk add --no-cache shadow keepassxc radare2 aws-cli geany git build-base && \
  echo "**** adding abc user to root for Docker ****" && \
  usermod -aG root abc && \
  touch /var/run/docker.sock && \
  chown abc:abc /var/run/docker.sock && \
  echo "**** cleanup ****" && \
  rm -rf /tmp/*

WORKDIR /config/Desktop

COPY src/main/resources/executables/*linux* /config/Desktop/wrongsecrets/
COPY src/main/resources/executables/decrypt /config/Desktop/wrongsecrets/
COPY src/main/resources/executables/wrongsecrets-advanced-c-windows.exe /config/Desktop/wrongsecrets/
COPY src/test/resources/alibabacreds.kdbx /var/tmp/helpers/
COPY src/test/resources/alibabacreds.kdbx /var/tmp/wrongsecrets/
COPY wrongsecret-desktop-resources/welcome.md /var/tmp/wrongsecrets/

RUN sudo chown abc /var/tmp/wrongsecrets

COPY wrongsecret-desktop-resources/startwm.sh /defaults/startwm.sh
