FROM lscr.io/linuxserver/webtop:4.16-r0-ls95
LABEL NAME="OWASP WrongSecrets Web Desktop" MAINTAINER="Jeroen Willemsen"

RUN \
   echo "*** install kubectl ***" && \
    curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl" &&\
    sudo install -o root -g root -m 0755 kubectl /usr/local/bin/kubectl &&\
    rm kubectl

RUN \
  echo "**** install packages ****" && \
  apk add --no-cache shadow keepassxc radare2 aws-cli geany git gdb build-base icu-libs icu-data-full ca-certificates libgcc libstdc++ zlib libintl musl-locales && \
  echo "**** adding abc user to root for Docker ****" && \
  usermod -aG root abc && \
  touch /var/run/docker.sock && \
  chown abc:abc /var/run/docker.sock && \
  echo "**** cleanup ****" && \
  rm -rf /tmp/*

RUN echo "**** clone wrongsecrets.git for webtop in k8s ****" && \
    mkdir /var/tmp/wrongsecrets && \
    cd /var/tmp/wrongsecrets && \
    git clone https://github.com/OWASP/wrongsecrets.git

RUN \
    echo "installing dotnet with musl compatibility" && \
    apk add --no-cache curl icu-libs krb5-libs libgcc libintl libssl1.1 libstdc++ zlib && \
    curl -sSL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel 6.0 --install-dir /etc/dotnet && \
    export DOTNET_ROOT=/etc/dotnet && \
    export PATH="/etc/dotnet:/etc/dotnet/tools:$PATH" && \
    echo "Checking dotnet installation..." && \
    /etc/dotnet/dotnet --info && \
    echo "Installing ilspycmd..." && \
    /etc/dotnet/dotnet tool install ilspycmd --version 9.0.0.7889 --tool-path /etc/dotnet/tools

WORKDIR /config/Desktop

# Add secret handling for challenge functionality
# Create the /app directory to store the secret
RUN mkdir -p /app

# Use a separate RUN command for --mount
RUN --mount=type=secret,id=mysecret \
    export SECRET_VALUE=$(cat /run/secrets/mysecret) && \
    echo $SECRET_VALUE >> /app/secret.txt

# Create directories for copied files
RUN mkdir -p /var/tmp/wrongsecrets /var/tmp/wrongsecrets/decrypt

COPY src/main/resources/executables/*linux-mus* /var/tmp/wrongsecrets/
COPY src/main/resources/executables/decrypt/ /var/tmp/wrongsecrets/decrypt/
COPY src/main/resources/executables/wrongsecrets-advanced-c-windows.exe /var/tmp/wrongsecrets/
COPY src/main/resources/executables/secrchallenge.md /var/tmp/wrongsecrets/
COPY src/main/resources/executables/secrchallenge.json /var/tmp/wrongsecrets/
COPY src/test/resources/alibabacreds.kdbx /var/tmp/wrongsecrets/
COPY wrongsecret-desktop-resources/welcome.md /var/tmp/wrongsecrets/


RUN sudo chown abc /var/tmp/wrongsecrets

COPY wrongsecret-desktop-resources/startwm.sh /defaults/startwm.sh

