FROM azul/zulu-openjdk-alpine:15

ARG argBasedPassword="default"
ARG argBasedVersion="0.0.0"
ENV ARG_BASED_PASSWORD=$argBasedPassword
ENV APP_VERSION=$argBasedVersion
ENV DOCKER_ENV_PASSWORD="This is it"

RUN echo "2vars"
RUN echo "$ARG_BASED_PASSWORD"
RUN echo "$argBasedPassword"

ADD target/secrettextprinter-0.0.2-SNAPSHOT.jar /application.jar
CMD java -jar -Dserver.port=$PORT -Dspring.profiles.active=without-vault application.jar