apiVersion: apps/v1
kind: Deployment
metadata:
  name: secret-challenge-53
  namespace: default
spec:
  progressDeadlineSeconds: 20
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: secret-challenge-53
  template:
    metadata:
      labels:
        app: secret-challenge-53
      name: secret-challenge-53
    spec:
      securityContext:
        runAsUser: 2000
        runAsGroup: 2000
        fsGroup: 2000
      containers:
      - image: jeroenwillemsen/wrongsecrets-challenge53:1.12.0
        name: secret-challenge-53
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: '32Mi'
            cpu: '50m'
            ephemeral-storage: '100Mi'
        securityContext:
          capabilities:
            drop:
              - ALL
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsNonRoot: true
          privileged: false
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
          - name: shared-data
            mountPath: /shared-data
        command: ["/bin/sh", "-c"]
        args:
          - cp /home/wrongsecrets/* /shared-data/ && exec /home/wrongsecrets/start-on-arch.sh
      - image: jeroenwillemsen/wrongsecrets-challenge53-debug:1.12.0
        name: sidecar
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "-c", "while true; do ls /shared-data; sleep 10; done"]
        volumeMounts:
          - name: shared-data
            mountPath: /shared-data
      volumes:
        - name: 'ephemeral'
          emptyDir: { }
        - name: shared-data
          emptyDir: { }
