version: '3.8'

services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: wrongsecrets
      POSTGRES_PASSWORD: sdfjklhjUYYkghjv;-jhkf
      POSTGRES_DB: Acme
    ports:
      - "5432:5432"
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
