apiVersion: v1
kind: Service
metadata:
  name: wrongsecrets-llama
  labels:
    app: wrongsecrets-llama
spec:
  type: ClusterIP
  selector:
    app: wrongsecrets-llama
  ports:
    - name: http
      port: 1234
      targetPort: http
      protocol: TCP