output "cluster_endpoint" {
  description = "Endpoint for EKS control plane."
  value       = module.eks.cluster_endpoint
}

output "cluster_security_group_id" {
  description = "Security group ids attached to the cluster control plane."
  value       = module.eks.cluster_security_group_id
}

output "kubectl_config" {
  description = "kubectl config as generated by the module."
  value       = module.eks.kubeconfig
}

output "config_map_aws_auth" {
  description = "A kubernetes configuration to authenticate to this EKS cluster."
  value       = module.eks.config_map_aws_auth
}

output "fargate_profile_arns" {
  description = "Outputs from node groups"
  value       = module.eks.fargate_profile_arns
}

output "irsa_role" {
  description = "The role ARN used in the IRSA setup"
  value       = aws_iam_role.irsa_role.arn
}

output "secrets_manager_secret_name" {
  description = "The name of the secrets manager secret"
  value       = aws_secretsmanager_secret.secret.name
}
