<<<<<<< HEAD
*Why Key Derivation Functions are not safe when using hardcoded values*

Key Derivation Functions (KDFs) are deterministic. This means that they will always give back the same output for a given input. So, if the parameters are hardcoded, anyone with access to the code can run the KDF with the specified parameters and get the key.

KDFs should be used to generate keys based on dynamic input, such as human-supplied passwords. KDFs might be used when secure random sources can be used to generate keys. Again, the KDF's input is not hardcoded/deterministic in both cases.
=======
*Why you should be careful with Git notes?*

When developers use Git notes they can also expose secrets if developers inadvertently include sensitive information, such as passwords or API keys, in the notes.
Unlike regular commits, notes are not easily visible in code reviews, so they can go unnoticed for a long time.

Although manually going through Git notes to look for secrets would be cumbersome, there are many tools attackers could use to search through Git repo's to look for these leaked secrets.
>>>>>>> cefa8809 ( Feature(#614): Added test files)
