=== Вступний виклик

Ласкаво просимо до вступного виклику OWASP WrongSecrets!

У цьому виклику ми пояснюємо все, що вам потрібно знати для гри в OWASP WrongSecrets.

Кожен виклик полягає у знаходженні секрету, який не був добре прихований та/або налаштований у нашому https://github.com/OWASP/wrongsecrets[коді програми], https://hub.docker.com/r/jeroenwillemsen/wrongsecrets[контейнері Docker] або в одній з пов'язаних частин https://github.com/OWASP/wrongsecrets#table-of-contents[системи].

Коли ви знайдете секрет, введіть його у поле нижче та натисніть «Надіслати». Кнопка «Очистити» очистить поле введення.
Хочете зіграти знову? Натисніть кнопку «Скинути».

Правильна відповідь нижче — `The first answer`. Скопіюйте її у поле та натисніть «Надіслати».

Бажаємо успіхів у складніших викликах ;-).

Примітка: деякі наступні виклики потребують додаткових інструментів. Не хочете встановлювати їх самостійно? Скористайтеся контейнером:

[source, shell]
docker run -p 3000:3000 -v /var/run/docker.sock:/var/run/docker.sock jeroenwillemsen/wrongsecrets-desktop:latest


Потім у браузері перейдіть на http://localhost:3000[http://localhost:3000], щоб знайти webtop з усіма необхідними інструментами.
