apiVersion: v1
kind: Service
metadata:
  name: challenge74-llama
  labels:
    app: challenge74-llama
spec:
  selector:
    app: challenge74-llama
  ports:
    - name: http
      port: 1234
      targetPort: 1234
      protocol: TCP
  type: ClusterIP
