name: Build and Deploy Preview

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - 'src/main/resources/templates/**'
      - 'src/main/resources/static/**'
      - 'src/main/resources/explanations/**'

jobs:
  build-preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 23
        uses: actions/setup-java@v4
        with:
          java-version: "23"
          distribution: "oracle"
          cache: "maven"

      - name: Extract version from pom.xml
        id: extract-version
        run: |
          echo "Extracting version from pom.xml..."
          chmod +x ./mvnw
          VERSION=$(./mvnw help:evaluate -Dexpression=project.version -q -DforceStdout)
          DOCKER_VERSION=${VERSION%-SNAPSHOT}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "docker_version=$DOCKER_VERSION" >> $GITHUB_OUTPUT
          echo "Detected version: $VERSION"
          echo "Docker version: $DOCKER_VERSION"

      - name: Build application
        run: |
          echo "Building WrongSecrets application..."
          ./mvnw --no-transfer-progress clean package -DskipTests
          echo "Build completed. Checking target directory..."
          ls -la target/
          echo "JAR file details:"
          ls -la target/*.jar || echo "No JAR files found in target/"

      - name: Build Docker image
        run: |
          echo "Building Docker image with version ${{ steps.extract-version.outputs.docker_version }}..."
          docker build --build-arg argBasedVersion="${{ steps.extract-version.outputs.docker_version }}" -t wrongsecrets-preview .
          echo "Docker image built successfully"
          docker save wrongsecrets-preview > wrongsecrets-preview.tar

      - name: Upload preview artifact
        uses: actions/upload-artifact@v4
        with:
          name: wrongsecrets-preview-${{ github.event.number }}
          path: wrongsecrets-preview.tar

      - name: Comment on PR with instructions
        uses: actions/github-script@v7
        with:
          script: |
            const comment = `🔨 **Preview Build Complete!**

            Your changes have been built successfully. To test locally:

            \`\`\`bash
            # Download the artifact and load the Docker image
            docker load < wrongsecrets-preview.tar
            docker run -p 8080:8080 wrongsecrets-preview
            \`\`\`

            Then visit: http://localhost:8080

            **Changed Files in this PR:**
            - Templates: ${{ github.event.pull_request.changed_files }}

            ---
            <sub>Build completed by GitHub Actions</sub>`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
