# This is a basic workflow that is manually triggered

name: CodeClimate Standalone workflow

on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    tags:
      - '*'
  pull_request:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  code-quality:
    name: Code Climate Standalone
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Code Climate
        uses: erzz/codeclimate-standalone@v0.0.3
        with:
          html_report: true
          info_threshold: 50
          minor_threshold: 25
          major_threshold: 10
          critical_threshold: 5
          blocker_threshold: 1

      - name: Upload Report
        uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Code Climate Report
          path: |
            codeclimate-report.json
            codeclimate-report.html
