# This is a basic workflow that is manually triggered

name: CodeClimate Standalone workflow

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
permissions:
  contents: read
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  code-quality:
    name: Code Climate Standalone
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Code Climate
        uses: erzz/codeclimate-standalone@v0.0.5
        with:
          html_report: true
          info_threshold: 50
          minor_threshold: 25
          major_threshold: 30
          critical_threshold: 5
          blocker_threshold: 1

      - name: Upload Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Code Climate Report
          path: |
            codeclimate-report.json
            codeclimate-report.html
