name: Qodana
on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
  push:
    branches:
      - dev
      - master

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2023.3
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN_459528233 }}
