name: Leaked Secrets Scan With Trufflehog
on:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  TruffleHog:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: experiment-bed
          head: HEAD
          extra_args: --debug --only-verified
