name: GitHub actions schedule
run-name: Run GitHub actions in schedule 🕒

on:
  schedule:
    - cron: "*/5 * * * *"

jobs:
  Run-GitHub-Actions-Schedule:
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 Runs every 5 minutes"
